/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated.materiais'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated.caixa'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated.kanban'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated.orcamentos.index'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated.orcamentos.$id'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated.os.index'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated.os.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOrcamentosIndexRoute = AuthenticatedOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOrcamentosIdRoute = AuthenticatedOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/': typeof AuthenticatedOsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os': typeof AuthenticatedOsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clientes' | '/materiais' | '/equipe' | '/caixa' | '/kanban' | '/orcamentos/$id' | '/orcamentos/' | '/os/$id' | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/materiais' | '/equipe' | '/caixa' | '/kanban' | '/orcamentos/$id' | '/orcamentos' | '/os/$id' | '/os'
  id: '__root__' | '/_authenticated' | '/_authenticated/' | '/_authenticated/clientes' | '/_authenticated/materiais' | '/_authenticated/equipe' | '/_authenticated/caixa' | '/_authenticated/kanban' | '/_authenticated/orcamentos/$id' | '/_authenticated/orcamentos/' | '/_authenticated/os/$id' | '/_authenticated/os/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

export interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedClientesRoute,
  AuthenticatedMateriaisRoute,
  AuthenticatedEquipeRoute,
  AuthenticatedCaixaRoute,
  AuthenticatedKanbanRoute,
  AuthenticatedOrcamentosIdRoute,
  AuthenticatedOrcamentosIndexRoute,
  AuthenticatedOsIdRoute,
  AuthenticatedOsIndexRoute,
}

export const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)
